name: sumup_flutter
description: Bridge with native Sumup SDK, supporting Air, Air Lite or PIN+ Terminal
version: 0.0.1
author: Florent Huran
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: florent.sumup_flutter
    pluginClass: SumupFlutterPlugin
